<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Torque_Scaling" Id="{8e970592-64c0-43ad-8110-566d9f1a776b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Torque_Scaling
VAR
	Rotor_Actual_Torque_Scaled : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Rotor_Actual_Torque_Scaled := INT_TO_REAL(GVL_Pelletizer.MyPelletizer.Rotor_VFD.VFD_Actual_Torque) / 10;]]></ST>
    </Implementation>
    <LineIds Name="Torque_Scaling">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>