<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Vision_GUI_Control" Id="{87634a6b-c49e-421c-811e-918241457a4d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Vision_GUI_Control
VAR


	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Vision_GUI_Control">
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>